name       : libvdpau
version    : 1.1.1
release    : 9
source     :
    - git|https://anongit.freedesktop.org/git/vdpau/libvdpau.git : a21bf7aa438f5dd40d0a300a3167aa3d6f26dccc
homepage   : http://people.freedesktop.org/~aplattner/vdpau
license    :
    - MIT
component  : xorg.display
summary    : Video Decode and Presentation API for Unix
description: |
    VDPAU is the Video Decode and Presentation API for UNIX. It provides an interface to video decode acceleration and presentation hardware present in modern GPUs.
emul32     : yes
builddeps  :
    - pkgconfig32(x11)
    - pkgconfig(dri2proto)
    - pkgconfig32(xext)
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-default-configuration-in-absence-of-config-file.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rfv $installdir/etc
