name        : libvdpau
version     : 1.1.1
release     : 3
source      :
    - http://people.freedesktop.org/~aplattner/vdpau/libvdpau-1.1.1.tar.bz2 : 857a01932609225b9a3a5bf222b85e39b55c08787d0ad427dbd9ec033d58d736
homepage    : http://people.freedesktop.org/~aplattner/vdpau
license     :
    - Public-Domain
    - GPL-3.0+
builddeps   :
    - pkgconfig(x11)
    - pkgconfig(dri2proto)
    - pkgconfig(xext)
summary     : Video Decode and Presentation API for Unix
description : |
    Video Decode and Presentation API for Unix
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
