name       : libvdpau
version    : '1.3'
release    : 12
source     :
    - https://gitlab.freedesktop.org/vdpau/libvdpau/-/archive/1.3/libvdpau-1.3.tar.bz2 : b5a52eeac9417edbc396f26c40591ba5df0cd18285f68d84614ef8f06196e50e
homepage   : http://people.freedesktop.org/~aplattner/vdpau
license    : MIT
component  : xorg.display
summary    : Video Decode and Presentation API for Unix
description: |
    VDPAU is the Video Decode and Presentation API for UNIX. It provides an interface to video decode acceleration and presentation hardware present in modern GPUs.
emul32     : yes
builddeps  :
    - pkgconfig32(x11)
    - pkgconfig32(xext)
    - pkgconfig(dri2proto)
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-default-configuration-in-absence-of-config-file.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -fr $installdir/etc/
