name        : libvdpau
version     : 1.1.1
release     : 5
source      :
    - http://people.freedesktop.org/~aplattner/vdpau/libvdpau-1.1.1.tar.bz2 : 857a01932609225b9a3a5bf222b85e39b55c08787d0ad427dbd9ec033d58d736
homepage    : http://people.freedesktop.org/~aplattner/vdpau
license     :
    - Public-Domain
    - GPL-3.0+
builddeps   :
    - pkgconfig32(x11)
    - pkgconfig(dri2proto)
    - pkgconfig32(xext)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32      : yes
summary     : Video Decode and Presentation API for Unix
description : |
    Video Decode and Presentation API for Unix
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
